newtmgr/cli/connprofile.go, newtmgr/config/connprofile.go
Print error when user does not provide **type** or **connstring** to `newtmgr conn add` command.
=> Mynewt-693 - error check for type and connstring.

newtmgr/cli/image.go
Added more help text to explain when an image can be erased and matches documentation.
=> MYNEWT-768 help text for newtmgr image erase command.

newtmgr/cli/connprofile.go
The usage for the optional "name" variable in the "newtmgr conn add" command seems redundant and confusing. When the variable is set in the command, the value overrides the required <conn_profile> parameter. The user must then use the value specfied for the name variable and not the <conn_profile> value to refer the connection profile.  It seems the user can just specify the name he wants to use in the <conn_profile>.
Chris and I discussed this and decided to remove the variable to simply documentation.
=> Remove optional name variable in newtmgr conn add command

newtmgr/cli/commands.go, newtmgr/cli/config.go, newtmgr/cli/crash.go, newtmgr/cli/datetime.go, newtmgr/cli/echo.go, newtmgr/cli/fs.go, newtmgr/cli/image.go, newtmgr/cli/log.go, newtmgr/cli/mpstat.go, newtmgr/cli/reset.go, newtmgr/cli/run.go, newtmgr/cli/stat.go, newtmgr/cli/taskstat.go
Some help text updates added for newtmgr commands for 1.0 (newt repos) did not get merged into the newtmgr repo.  This PR merges the help text updates from 1.0 newt repo to the newtmgr repo.
=> Merge 1.0 newtmgr help text updates into new newtmgr repo

newtmgr/bll/bll_sesn_cfg.go
Under linux, the currantlabs/ble library was rejecting an attempt to set an ATT MTU > 512 with the error "Invalid argument".
=> Reduce default MTU from 527 to 512.

Makefile
So we don't have to create a Makefile each time we build a newtmgr deb package
=> Makefile file for creating newtmgr deb package

nmxact/nmble/conn.go
BleDev, instead of value. Change the call to printf() to pass pointer
to peer, instead of it's value.
=> conn.go; BleDev.String() in bledefs/bledefs.go takes in pointer to

nmxact/nmble/ble_xport.go, nmxact/nmble/sync.go
This prevents a hang that occurs due to the following sequence:
1. BLE transport successfully starts.
2. For some reason, the transport needs to be reset.
3. Blehostd fails to start.
Step 3 triggers a transport shutdown.  Prior to this change, the
transport might appear to still be in sync, which causes the transport
to send a `reset` command to blehostd.  Since blehostd is not running,
the code hangs.
=> nmxact - Stop syncer on xport startup.

nmxact/nmble/ble_act.go
When blehostd sends a `conn_cancel_evt` event, it uses the sequence
number associated with the connection, not the sequence number
corresponding to the `conn_cancel` request.
Prior to this change, nmxact would listen for the `conn_cancel_evt` with
a sequence number equal to that of the request.  The event would never
arrive, which caused the transport to be restarted.
Now, the connect listener listens for the cancel event, in addition to
the connect event.
=> nmxact - conn_cancel_evt listener uses wrong seq

newtmgr/cli/image.go, newtmgr/config/serial_config.go, nmxact/nmserial/serial_sesn.go, nmxact/nmserial/serial_xport.go, nmxact/xact/image.go
newtmgr. Add '-e' flag to image upload which stops upload from
starting with erase flash command.
=> image upload; add support for specifying max mtu to use for serial

newtmgr/cli/commands.go, newtmgr/cli/common.go, newtmgr/config/connprofile.go, newtmgr/nmutil/nmutil.go
This commit adds three CLI options:
```
--connextra string    Additional key-value pair to append to the connstring
--connstring string   Connection key-value pairs to use instead of using the profile's connstring
--conntype string     Connection type to use instead of using the profile's type
```
`--conntype` and `--connstring` replace the `type` and `connstring`
values of the connection profile.  If no connection profile is
specified, these options must specify all the necessary connection
settings.
`--connextra` appends fields to the connection profile's `connstring`
value.  This option is only useful when a connection profile is
specified.
=> newtmgr - CLI options to specify connprofile flds

nmxact/nmble/ble_proto.go, nmxact/nmble/ble_util.go, nmxact/nmble/naked_sesn.go, nmxact/nmxutil/nmxerr.go
```
// Represents a BLE pairing failure due to missing or mismatched key material.
type BleSecurityError struct {
Text string
}
```
=> nmxact - Error type representing a failure to pair

nmxact/mgmt/mgmt.go, nmxact/xact/fs.go, nmxact/xact/image.go
Also remove functions which appear to not be used.
=> nmxact; image upload with oic would always try to use Coap over TCP encoding.

nmxact/nmserial/serial_xport.go
Sometimes RX buffer contain unread bytes with
cause failures of the firs transaction. This patch
fix this this problem by flushing the port prior
any operation.
=> Flush the serial port before operation

newtmgr/cli/commands.go, newtmgr/cli/connprofile.go, newtmgr/cli/crash.go, newtmgr/cli/datetime.go, newtmgr/cli/fs.go, newtmgr/cli/image.go, newtmgr/cli/log.go, newtmgr/cli/run.go, newtmgr/config/connprofile.go, newtmgr/newtmgr.go, newtmgr/nmutil/nmutil.go
This allows the tool name and version number to be changed at runtime.  This is required for other tools that want to depend on parts of newtmgr without pulling in confusing help messages.
The specific use case here is the mcumgr CLI tool.
=> newtmgr - Allow metadata to be configured at runtime

newtmgr/config/connprofile.go
Result is that newtmgr cannot find existing connection profiles file.
=> newtmgr; connProfileCfgFilename() was omitting "/" between dir and filename.

newtmgr/cli/res.go, nmxact/xact/res.go
So users of nmxact library don't need to modify their code to set Observe to -1 to prevent it from happening.
=> nmxact; default observe off when creating CoAP get command.

newtmgr/cli/commands.go, newtmgr/cli/interactive.go
The newtmgr codebase is used in two tools:
* newtmgr
* mcumgr
An earlier commit (a895655ebc82d0c57c15ae29eea68536c10b8a70) allowed the
application to configure its own name for displaying help messages
properly.  A few instances of "newtmgr" were missed in that commit.
This commit catches the remaining instances.
=> Remove hardcoded "newtmgr" strings.

newtmgr/bll/bll_xport.go, newtmgr/bll/bll_xport_linux.go, newtmgr/bll/bll_xport_nonlinux.go, newtmgr/cli/common.go, newtmgr/config/bll_config.go
Prior to this commit, newtmgr always used a public address to connect.
This commit makes two changes (Linux only):
* allows the user to specify own address type with the `own_addr_type` connection setting.
* uses a value of 0x10 (10 ms) for the scan interval and scan window (was: 2.5 ms for both).
These changes only have an effect in Linux.  In macOS, the CoreBluetooth library does not allow these settings to be specified at connect time.
=> bll - Allow OwnAddrType to be specified in linux.

nmxact/mtech_lora/mtech_lora_sesn.go
overflows if device is not reachable.
=> mtech_lora; flush deveui out queue on close. LNS queue eventually

newtmgr/bll/bll_sesn.go, newtmgr/bll/bll_sesn_cfg.go, nmxact/mgmt/mgmt.go, nmxact/mgmt/transceiver.go, nmxact/mtech_lora/mtech_lora_sesn.go, nmxact/nmble/ble_sesn.go, nmxact/nmble/naked_sesn.go, nmxact/nmcoap/nmcoap.go, nmxact/nmserial/serial_sesn.go, nmxact/omp/dispatch.go, nmxact/omp/omp.go, nmxact/sesn/sesn.go, nmxact/sesn/sesn_cfg.go, nmxact/udp/udp_sesn.go
Support setting a transmit and receive callback for newtmgr CoAP
messages. This enables filtering the messages to do encryption, logging,
metrics, etc. The TxFilterCb and RxFilterCb are set in SesnCfg.
=> Filter newtmgr CoAP messages

newtmgr/bll/bll_xports_windows.go, newtmgr/config/bll_config_windows.go
BllConfig and XportCfg on Windows stubs were not extendended with
new members.
=> Fix build on Windows

nmxact/nmp/image.go, nmxact/xact/image.go
When uploading image, 1st chunk will include "datahash" field which is
simply SHA-256 calculated over complete data to be uploaded (so it is
not the same as image hash). This field can be then used by imgmgr on
target to detect whether the same data is being uploaded and possibly
resume transfer which was interrupted previously.
=> nmxact: Add data hash to 1st chunk of image upload data

nmxact/nmp/config.go, nmxact/nmp/crash.go, nmxact/nmp/datetime.go, nmxact/nmp/echo.go, nmxact/nmp/fs.go, nmxact/nmp/image.go, nmxact/nmp/log.go, nmxact/nmp/mpstat.go, nmxact/nmp/reset.go, nmxact/nmp/run.go, nmxact/nmp/stat.go, nmxact/nmp/taskstat.go, nmxact/omp/omp.go, nmxact/xact/image.go
The main issue fixed here is that when using NMP over OIC empty fields in requests were not skipped properly since this should be done automatically with `omitempty` option in `codec` tag, but this tag was in fact ignored during encoding. This is now fixed by using small trick with structs package.
Also, due to invalid check, `image upload` always included `len` and `datahash` fields in every chunk of data and this is now also fixed so some bytes are saved over the air.
Tested using few commands via `ble` and `oic_ble` connection types.
=> Fixes in NMP encoding code

newtmgr/cli/res.go
Prior to this commit, newtmgr assumed the value in a res key-value-pair was a string.  So, the following command:
```
res put public myresource key=1
```
would include the string "1" in the PUT request.
This commit changes this behavior such that newt encodes integers as numbers in the CoAP request.  To force the string type, enclose the value in double-quotes, e.g.,
```
res put public myresource 'key="1"'
```
=> res - Allow integer values

nmxact/nmp/image.go, nmxact/xact/image.go
Let's use "sha" instead of "datahash" to keep it short.
Long name like "datahash" not only adds few unnecessary bytes to data
stream but also makes image upload fail with MCUBoot which does not
handle long key names (no need to change it there though).
"sha" name was chosen as it is short and should not be confused with
image hash which is something different since data hash is computed
over whole upload data, i.e. image with trailing data etc.).
This fixes https://github.com/apache/mynewt-mcumgr-cli/issues/2.
=> nmxact: Make field name for uploaded data hash shorter

newtmgr/config/ble_config.go, newtmgr/config/bll_config.go
This specifies the connection timeout, in seconds.  E.g.,
```
newtmgr --conntype ble --connstring peer_name=mydev,conn_timeout=23.54' -t 4 echo a
```
This command allows 23.54 seconds for the BLE connection to be established.  Upon sending the echo request, newtmgr waits four seconds before reporting a response timeout.
In addition, if the `conn_timeout` setting is not specified, it defaults to the response timeout value (`-t`).
=> Allow "conn_timeout" for ble and bll types.

nmxact/nmp/log.go
This PR fixes a bug where newtmgr could not retrieve logs from a device using a `LOG_VERSION` of 3:
```
[ccollins@ccollins-mac:~/repos/juul-platform]$ newtmgr -ldebug --conntype oic_ble --connstring peer_name=cc log show
DEBU[2018-07-10 10:41:47.863] Using connection profile: name=unnamed type=oic_ble connstring=peer_name=cc
DEBU[2018-07-10 10:41:47.864] {add-oic-listener} [transceiver.go:64] token=[]
DEBU[2018-07-10 10:41:47.864] Connecting to peer
DEBU[2018-07-10 10:41:48.514] Exchanging MTU
DEBU[2018-07-10 10:41:48.514] Exchanged MTU; ATT MTU = 104
DEBU[2018-07-10 10:41:48.514] Discovering profile
DEBU[2018-07-10 10:41:48.823] Subscribing to NMP response characteristic
DEBU[2018-07-10 10:41:48.943] {add-nmp-listener} [bll_sesn.go:415] seq=66
DEBU[2018-07-10 10:41:48.943] Serialized OMP …
```
=> Fix [un]marshal of log-entry-type

newtmgr/cli/res.go
This commit allows newtmgr to parse boolean values in a res
key-value-pair. The boolean value is case-insensitive, but must match
completely (i.e. true, false).
=> res - Allow boolean values

newtmgr/cli/res.go
This commit adds an optional flag for res commands and shows
additional details about the CoAP response. Currently, only the CoAP
code is shown with the flag, while the GET command also shows the Token
if it exists. This is based on the struct of *Cmd*ResResult.
=> res - add details flag for res commands

newtmgr/cli/interactive.go, newtmgr/cli/res.go, nmxact/sesn/sesn_cfg.go
Removes type field from res and interactive commands as it is not used anymore.
As a result, this also removes ParseResType.
=> res - remove type from res commands

nmxact/nmserial/serial_xport.go
If the port is already open, a second attempt is now a no-op.
=> nmserial: Don't attempt to open serial port twice

newtmgr/cli/image.go, nmxact/nmp/image.go, nmxact/xact/image.go
This commit adds an additional boolean field to the "image upload" request: `upgrade`.  If this field is true, the firmware will only accept an upload attempt if the new image's version number is greater
than that of the currently running image (using a semver-compatible comparision).
If the `upgrade` field is false or missing, no version check is performed.
The firmware only processes the `upgrade` field on the first image chunk.  It is harmless, but pointless, for a client to specify `upgrade` in any subsequent chunks.
=> Allow upgrade-only requests

newtmgr/cli/commands.go, nmxact/nmxutil/nmxutil.go, nmxact/omp/dispatch.go, nmxact/omp/omp.go
This commit adds the `--ompres` (OMP resource) command line switch.  If specified, newtmgr sends its OMP request to the specified resource instead of `/omgr`.
=> Allow alternate omgr resource

newtmgr/cli/res.go
The CoAP spec does not require PUT and POST requests to contain a body.  If the user doesn't specify any key-value pairs, send an empty request.
=> Allow empty PUT and POST requests

go.mod, go.sum
Update here and on newt to the same version; should fix build conflicts in tooling that requires both packages, like it happens for `mcumgr-cli`.
=> Update go/codec requirement to v1.1.7

newtmgr/cli/commands.go, newtmgr/cli/shell.go, nmxact/nmp/decode.go, nmxact/nmp/defs.go, nmxact/nmp/run.go, nmxact/nmp/shell.go, nmxact/xact/shell.go
This command executes the specified CLI command on the target device. The response contains the CLI output that would have been sent to the console.
Example usage:
```
newtmgr --conntype oic_ble --connstring peer_name=mydev shell exec stat ble_gattc
```
A different PR adds the `shell exec` command handler to mynewt-core: https://github.com/apache/mynewt-core/pull/1809
=> Add new command: `shell exec`

newtmgr/bll/bll_sesn.go, nmxact/bledefs/bledefs.go, nmxact/mtech_lora/mtech_lora_sesn.go, nmxact/nmble/ble_sesn.go, nmxact/nmble/ble_util.go, nmxact/nmble/naked_sesn.go, nmxact/nmserial/serial_sesn.go, nmxact/sesn/sesn.go, nmxact/sesn/sesn_cfg.go, nmxact/sesn/sesn_util.go, nmxact/udp/udp_sesn.go, nmxact/xact/res.go
This PR removes a feature that has been unused for years.
Initially, the idea was that each CoAP resource would be defined with one of the following security levels:
* public (no security)
* unauthenticated (encryption)
* secure (encryption and authentication)
A session (connection) would be secured in a transport-specific way, but the main transport under consideration was Bluetooth.  In Bluetooth, characteristics are assigned security levels resembling the three above. To implement this defunct security mechanism in CoAP-over-Bluetooth, we would need three different characteristics, one corresponding to each security level.  When sending a CoAP request, the newtmgr client would choose the correct characteristic based on the secure state of the connection.
This security policy has not …
=> Remove security requirements from CoAP commands

go.mod, go.sum, newtmgr/bll/bll_sesn.go, newtmgr/cli/interactive.go, newtmgr/cli/res.go, nmxact/mgmt/transceiver.go, nmxact/mtech_lora/mtech_lora_sesn.go, nmxact/nmble/ble_sesn.go, nmxact/nmble/naked_sesn.go, nmxact/nmcoap/dispatch.go, nmxact/nmcoap/frag.go, nmxact/nmcoap/listener.go, nmxact/nmcoap/nmcoap.go, nmxact/nmp/nmp.go, nmxact/nmserial/serial_sesn.go, nmxact/nmxutil/nmxutil.go, nmxact/omp/dispatch.go, nmxact/omp/omp.go, nmxact/sesn/sesn.go, nmxact/sesn/sesn_util.go, nmxact/udp/udp_sesn.go, nmxact/xact/res.go, nmxact/xact/xact.go
This is a massive PR.
This PR changes the CoAP functions in the `sesn` interface.  In particular, it replaces the old API with three low-level functions:
```
// Creates a listener for incoming CoAP messages matching the
// specified criteria.
ListenCoap(mc nmcoap.MsgCriteria) (*nmcoap.Listener, error)
// Cancels the CoAP listener with the specified criteria.
StopListenCoap(mc nmcoap.MsgCriteria)
// Transmits a CoAP message.
TxCoap(m coap.Message) error
```
Helper functions that combine these operations in useful ways are implemented in `sesn/sesn_util.go`.
Prior to this change, `sesn` contained only two CoAP functions:
```
TxCoapOnce(m coap.Message,
opt TxOptions) (coap.COAPCode, []byte, error)
TxCoapObserve(m coap.Message, opt TxOptions, NotifCb GetNotifyCb,
stopsignal chan int) …
```
=> nmxact: API change for CoAP operations

nmxact/nmcoap/listener.go, nmxact/nmserial/serial_xport.go
There is a max of one active session per serial transport.  This limitation is necessary because there is no demuxing protocol.  Whatever data is received over serial is just forwarded to the active session.
Before this commit, nmxact required the active sesion to unregister itself before any session could be registered again, even if the two sessions are the same.
This commit relaxes this restriction.  Now, it is OK to register the same session multiple times without unregistering in between.
This change is necessary due to the recent change to the session API.  Now, listening and transmitting are separate operations, so it is not trivial to arrange for a session to be unregistered after use.  In practice, there is never more than one serial session anyway.
=> nmxact: Don't require serial session to "unlisten"

newtmgr/cli/log.go, nmxact/nmp/log.go
The Mynewt log entry header optionally includes an "imghash" field. This field contains a truncated hash of the build that was running when the entry was logged.  If an entry contains this hash, the Mynewt device includes it in a `log show` response.
This PR changes newtmgr to print the image hash when it sees it in a `log show` response.
=> Include imghash in log show output

nmxact/mgmt/transceiver.go, nmxact/nmcoap/dispatch.go, nmxact/nmcoap/listener.go, nmxact/nmxutil/nmxutil.go, nmxact/omp/dispatch.go, nmxact/omp/omp.go
Prior to this change, nmxact created a single CoAP listener to handle all incoming OMP responses.  This listener would parse the embedded NMP message, then dispatch to the appropriate NMP listener based on the NMP sequence number.
There is a problem with this approach.  If the server rejects an outgoing OMP request with a CoAP error (e.g., the omp resource requires a more secure connection), then the error does not get passed up to the caller.  The error response does not contain an embedded NMP response, so there is no way to match it with the appropriate listener.  The result is that nmxact drops the CoAP error, and the OMP operation eventually times out.
This PR makes the following changes:
* Every outgoing OMP request contains a single-byte token consisting of the NMP sequence number. …
=> nmxact: Create a listener for each OMP response

README.md, docs/install/install_linux.rst, docs/install/install_windows.rst
Now that newtmgr uses modules instead of a vendor directory, module support needs to be enabled to build newtmgr.
This setting is only necessary for older versions of go.  In newer versions, the setting is enabled by default (outside of the GOPATH). Maybe we can revert this change once modules become fully mainstream.
=> README: Indicate that GO111MODULE must be set

newtmgr/cli/res.go
If the user issues a `res` command with no payload (e.g., `res get /my/resource`), the outgoing command should not have a payload.
Instead, newtmgr was encoding an empty map as the payload.
=> res: Don't include payload if none specified

newtmgr/cli/image.go, nmxact/nmp/image.go, nmxact/xact/image.go
This makes `image list` and `image upload` compatible with MCUBoot's `serial_boot` when working in a multi-image setting.
The image state CBOR packet and image upload were both update to carry an extra field called "image" whose number indicates which image set is being handled. If absent, image 0 is used for compatibility.
The upload command got and extra parameter `-n` (or `--image`) to set which image is being sent, eg, `newtmgr image -n1 upload <fw.img>`.
The image list command now prints "image=X slot=Y", eg:
```
Images:
image=0 slot=0
version: 1.7.0.0
bootable: false
flags:
hash: Unavailable
image=0 slot=1
version: 1.4.0.0
bootable: false
flags:
hash: Unavailable
image=1 slot=0
version: 1.8.0.0
bootable: false
flags:
hash: Unavailable
Split status: N/A (0)
```
=> [RFC] Add basic multi-image support

nmxact/xact/res.go
Prior to this PR, only 2.05 (Content) was considered success.  All other 2xx codes (e.g., Created, Valid, etc.) were treated as failures.
=> res: Interpret all 2xx codes as success

nmxact/omp/dispatch.go
This PR fixes this crash reported by @vrahane (note: paths obfuscated):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4450e4f]
goroutine 1 [running]:
<base>/vendor/mynewt.apache.org/newtmgr/nmxact/omp.(*Dispatcher).RemoveNmpListener(0xc0000c0700, 0x42, 0x0)
<home-base>/vendor/mynewt.apache.org/newtmgr/nmxact/omp/dispatch.go:180 +0xcf
<base>/vendor/mynewt.apache.org/newtmgr/nmxact/mgmt.(*Transceiver).txRxOmp(0xc0000c06c0, 0xc000069080, 0xc00000e500, 0x1fd, 0x2540be400, 0x0, 0x0, 0x487b0a0, 0xc000298080)
<home-base>/vendor/mynewt.apache.org/newtmgr/nmxact/mgmt/transceiver.go:152 +0x4ef
<base>/vendor/mynewt.apache.org/newtmgr/nmxact/mgmt.(*Transceiver).TxRxMgmt(0xc0000c06c0, 0xc000069080, …
```
=> omp: Don't dereference nil pointer

nmxact/nmp/image.go, nmxact/nmp/nmp.go, nmxact/omp/omp.go, nmxact/xact/image.go
nmxact generates several image upload requests for each one that it actually sends.  It does this to determine the ideal chunk size.
Each of these requests was consuming a sequence number.  As a result, the sequence number would increase by three for each request that was actually transmitted.
This PR changes the image upload command such that the sequence number is only increased when a request is actually sent.
This PR also removes the "Serialized OMP" debug log message.  This message got logged immediately before the request got transmitted.  The result was two nearly identical large log messages (both contain the full payload of the request).
=> nmxact: Don't skip seq numbers in `image upload`

newtmgr/cli/res.go
Prior to this PR, `res -j` would only accept a `map[string]interface{}` as the payload.  Now, it accepts an `interface{}`.  This allows the payload to consist of a number, a string, or an array (or an object, as before).
Also:
JSON only supports a single numeric type: "number".  When the `res -j` command parses a payload, the JSON unmarshal function parses all numbers as instances of float64.  This makes the resulting CBOR payload incorrect when the user just wants to use integers.
This PR adds an option to the res command: `--int`.  When specified, all numbers in the payload are converted to integers when the conversion does not result in a change in value.  For example, `1.0` is converted to an integer, but `1.5` is not.
=> res: When `-j` is specified, allow all value types 

newtmgr/cli/res.go
This command:
```
newtmgr res get /my/res
```
should send a CoAP GET request with *no* payload.  An optional payload can be specified with extra arguments after the resource name.  Since there are no extra arguments, there should be no payload.
Prior to this PR, newtmgr was including an empty map as the payload in such requests.
The bug was caused by this quirk in Go:
https://forum.golangbridge.org/t/a-nil-a-b-b-nil-with-pointers-and-interface/10593
In short, if `nil` is assigned to a variable of type `interface{}`, the variable will *not* compare equal to `nil`.  An interface variable contains two pieces of information: 1) its type, and 2) its value.  The variable is not equal to `nil` because `nil` is an *untyped* nil value.
The solution is to return the untyped `nil` rather than the …
=> res: Use zero payload when no args specified

go.mod, go.sum, newtmgr/cli/commands.go, newtmgr/cli/darwin.go, newtmgr/cli/notdarwin.go
This is a less buggy implementation of the mojave-support feature.  It
also adds some low level Bluetooth logging for macOS users (when -ldebug
is specified).
=> Use latest ble library (with cbgo)

docs/command_list/newtmgr_conn.rst
newtmgr (1.9.0-dev at least) doesn't allow the space between the command and baud.
=> Remove illegal space

newtmgr/bll/bll_sesn.go, newtmgr/bll/bll_sesn_cfg.go, newtmgr/cli/common.go, nmxact/mgmt/transceiver.go, nmxact/mtech_lora/mtech_lora_sesn.go, nmxact/nmble/ble_sesn.go, nmxact/nmble/naked_sesn.go, nmxact/nmcoap/nmcoap.go, nmxact/nmserial/serial_sesn.go, nmxact/nmserial/serial_xport.go, nmxact/omp/dispatch.go, nmxact/omp/omp.go, nmxact/sesn/sesn.go, nmxact/sesn/sesn_cfg.go, nmxact/udp/udp_sesn.go, nmxact/xact/image.go
To determine the correct amount of image data to put in an image upload request, newtmgr repeatedly generates requests until it finds the optimal value.  Each of these requests must be identical (aside from the payload size) or else the comparison is invalid.  If a `sesn`'s filter uses different parameters each time it encodes a message (e.g., if it does encryption), that breaks this method of determining the correct chunk size.
By freezing the filter, the same parameters get used for each subsequent message encoding.  This ensures the payload size won't change after we have settled on a chunk size.
=> Freeze filter for `image upload` chunk length calculation

nmxact/mgmt/transceiver.go
omp.EncodeOmpDgram now takes txFilter, not txFilterCb. Fix this.
Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>
=> transiever: fix compilation error

nmxact/xact/image.go
Reduce resolution of the integer variable MaxRxOff from 64-bit to 32-bit, to fix the issue where LoadInt64 crashes with a segmentation fault on Raspberry Pi 3B+ and other 32-bit ARM hardware. Addresses issue #171 .
=> Change MaxRxOff to be a 32-bit integer

go.mod, go.sum
Use the latest hash that includes Data Length Extension
Feature support for Linux.
Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>
=> go.mod: Update JuulLabs-OSS/ble hash

nmxact/nmble/naked_sesn.go, nmxact/udp/udp_sesn.go
This addresses the UDP based image upload failure.
The UDP and naked sessons do not implement TxRxAsync
for optimized transfer as in BLE, however, continue to
support the operation by calling TxRxMgmt.
Failure signature:
```
~/go/bin/mcumgr --conntype udp --connstring=[192.168.1.1]:1337 image
upload build_f429/smpsvr/zephyr/zephyr.signed.bin
0 / 90644
[-----------------------------------------]
0.00%
Error: ImageUpload unexpected error after 0/90644 bytes
```
Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>
=> nmxact: Fix image upload failure due to unsupported async method

newtmgr/bll/bll_sesn_cfg_windows.go
Commit 0663961 replaced callbacks
with interfaces (TxFilter and RxFilter). Apply the change for
the Windows specific implementation as well and fix the following
error.
```
C:\Users\ryan.erickson>go get github.com/apache/mynewt-mcumgr-cli/mcumgr
go\src\mynewt.apache.org\newtmgr\newtmgr\bll\bll_sesn_cfg_windows.go:35:15:
undefined: nmcoap.MsgFilter
go\src\mynewt.apache.org\newtmgr\newtmgr\bll\bll_sesn_cfg_windows.go:36:15:
undefined: nmcoap.MsgFilter
```
Building tested with:
`$GOOS=windows go build`
Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>
=> bll_sesn_cfg_windows: Fix build error for windows

newtmgr/cli/taskstat.go
- There was a space earlier and if the task name was bigger,
it would cause formatting issues
*BEFORE*
```
Vipuls-MacBook-Pro-16-inch-2019:fw-signal vipul$ mcumgr --conntype ble --connstring peer_name=pr-8c1b taskstat
task pri tid  runtime      csw    stksz   stkuse last_checkin next_checkin
BT ECC  10   2        0        0      275      223        0        0
BT RX 248   0        0        0     1024      105        0        0
BT RX pri 246   1        0        0      112       43        0        0
BT TX 247   3        0        0      160      102        0        0
idle 00  15   5        0        0       80       14        0        0
main   0   6        0        0     1024      358        0        0
sysworkq 255   4        0        0      512      153        0        0
```
*AFTER*
```
task …
```
=> taskstat: Add tab character after the task's name

nmxact/nmp/decode.go
This PR allows the to use custom  smp commands (e.g. using the peruser group). The implementation of the commands is not part of this PR since Go allowed me to extend the the library without forking the repo. The only thing that must be changed is the possibility to register the custom response handlers. @ccollins476ad could you please take a look at it?
=> nmp decode: allow registration of custom response handlers

nmxact/xact/image.go
This patch changes the hardcoded 3 seconds timeout to the timeout which is actually specified at the command line, or the default 10 seconds if nothing is specified. The 3 seconds was not enough to write a flash image, when the erase time needs longer, as it is the case with Zephyr, when the incrementally erase option is not enabled.
=> use the timeout from the command line

newtmgr/bll/bll_common.go, newtmgr/cli/commands.go, newtmgr/nmutil/nmutil.go, nmxact/xact/image.go
It seems like on newer versions of mac (e.g. Monterey) fix with looping three times to get right MTU doesn't work. Also for some strange reason default TxMTU is set to 17 instead of 23. Now user can set MTU from the command line (-m <MTU value>). If MTU is not set in the command line and after performing three loops MTU is still <23 we hardcode it to 185.
=> Fix not working MTU exchange on newer versions of mac

docs/command_list/newtmgr_mpstats.rst, docs/command_list/newtmgr_stat.rst, docs/command_list/newtmgr_taskstats.rst, docs/install/install_mac.rst, docs/install/install_windows.rst
Fixes broken references to other documents/sections. Removes emojis from code snippets causing issues with LaTeX output generated by Sphinx.
=> documentation/sphinx: Fix formatting errors in `.rst` files
