apache/mynewt-newtmgr

newtmgr/bll/bll_common.go, newtmgr/bll/bll_oic_sesn.go, newtmgr/bll/bll_plain_sesn.go, newtmgr/bll/bll_sesn_cfg_windows.go, newtmgr/bll/bll_util.go, newtmgr/bll/bll_xports_windows.go, newtmgr/config/bll_config.go, newtmgr/config/bll_config_windows.go
newtmgr on windows would not compile with currantlabs/ble package. Added windows version go files to exclude currantlabs/ble.
=> remove currantlabs/ble from windows

LICENSE
Signed-off-by: Fabio Utzig <utzig@apache.org>
=> Add license of all bundled packages

nmxact/nmble/naked_sesn.go
Prior to this commit, a panic like this would occur when a BLE session was
closed twice:
```
panic: close of closed channel
goroutine 54 [running]:
github.com/runtimeinc/rtgw/vendor/mynewt.apache.org/newtmgr/nmxact/nmble.(*NakedSesn).shutdown(0x10f33500, 0xa311b8, 0x10ec0080, 0x0, 0x0)
#011/gopath/src/github.com/runtimeinc/rtgw/vendor/mynewt.apache.org/newtmgr/nmxact/nmble/naked_sesn.go:153 +0x120
github.com/runtimeinc/rtgw/vendor/mynewt.apache.org/newtmgr/nmxact/nmble.(*NakedSesn).Open(0x10f33500, 0x0, 0x0)
#011/gopath/src/github.com/runtimeinc/rtgw/vendor/mynewt.apache.org/newtmgr/nmxact/nmble/naked_sesn.go:218 +0x184
github.com/runtimeinc/rtgw/vendor/mynewt.apache.org/newtmgr/nmxact/nmble.(*BleSesn).Open(0x10d11bc0, 0x0, 0x0)
#011/gopath/src/github.com/runtimeinc/rtgw/vendor/mynewt.apac …
```
=> Fix panic when BLE session is closed twice.

nmxact/nmble/naked_sesn.go
A half-implemented fix was mistakenly submitted in commit 355c9c83ff49a554db784ddcbfa77479a80fa8e6.  The resulting code generates "Attempt to use closed session" errors whenever a `BleSesn` is reused, even when the client previously called its `Close()` function.
This commit updates the codebase to the fully implemented and tested version of the fix.
=> BLE - Fix "Attempt to use closed session" error

newtmgr/cli/config.go, nmxact/nmp/config.go, nmxact/xact/config.go
=> nmxact; add option to include save command as part of config write.

newtmgr/bll/bll_sesn.go, newtmgr/config/mtech_lora_config.go, nmxact/lora/lora_coap.go, nmxact/mgmt/transceiver.go, nmxact/mtech_lora/listen.go, nmxact/mtech_lora/mtech_lora_sesn.go, nmxact/mtech_lora/mtech_lora_xport.go, nmxact/nmble/ble_sesn.go, nmxact/nmble/naked_sesn.go, nmxact/nmcoap/dispatch.go, nmxact/nmserial/serial_sesn.go, nmxact/nmserial/serial_xport.go, nmxact/omp/dispatch.go, nmxact/omp/omp.go, nmxact/sesn/sesn.go, nmxact/sesn/sesn_cfg.go, nmxact/udp/udp_sesn.go
Initial implementation is for Lora/serial only; BLE/UDP have transport level muxing mechanism which make this kind of support for those less necessary.
=> nmxact; add API to allow CoAP server side operation

newtmgr/cli/log.go, nmxact/nmp/log.go
- Add support for parsing log responses coming with types
- Type CBOR not supported
=> log handler: add support for type cbor parsing

nmxact/sesn/sesn.go
=> Allow default transmit options to be configured

nmxact/xact/image.go
This addresses problem found on MacOS when we cannot sent full image header in 1st chunk after `datahash` was added there. With this fix we'll just skip `datahash` if it cannot fit - resumue will not work, but upload will.
=> Fix image upload and resume

newtmgr/cli/res.go
Formats response payload into pretty JSON format with
indents and brackets.
=> res - add pretty JSON format to CoAP response

newtmgr/cli/common.go
=> newtmgr; add SetFilters() function to allow setting tx/rx filters for

nmxact/xact/image.go
Prior to this commit, newtmgr determined how many bytes of image data to include in an upload request as follows:
1. Choose a large number to start (512).
2. Encode the upload request into CoAP (+ optional security).
3. Compare the size of request to the transport's MTU. If the request is too large, subtract the difference from the chunk length.
Occasionally, the above procedure resulted in a request that was one byte too large.
This commit changes the above procedure such that it runs in a loop.  After reducing the chunk length, a new request is encoded and its length is compared to the MTU.  The loop executes until the encoded request fits within the MTU.
=> image: Multiple rounds of chunklen reduction

newtmgr/newtmgr.go
1.6 was released and so version on master should be bumped.
=> Update version string

newtmgr/cli/res.go
Before this commit, the `res` command accepted a payload in the form of `k=v` pairs, e.g.,
```
newtmgr res put /my/res a=start dur=1
```
This commit adds a new option to the `res` command: `-j`.  When this option is specified, the CoAP message body is expressed as a JSON string, e.g.,
```
newtmgr res -j put /my/res '{"a":"start","dur":1}'
```
This allows for more complex payloads, and it removes ambiguity about what data types are used.
=> res: `-j` option to specify payload as JSON

go.mod, go.sum, newtmgr/cli/interactive.go
fixes [issue 8 in mcumgr-cli.](https://github.com/apache/mynewt-mcumgr-cli/issues/8)
=> Depend on ishell.v2 (was: ishell.v1)

Makefile
=> Makefile: Update for compatibility with Go modules

newtmgr/cli/log.go, nmxact/xact/log.go
Normally, the `newtmgr log show` command only receives one packet's worth of log entries.
This PR adds a `-a` option to this command.  When this option is specified, newtmgr continues requesting more data until it reaches the end of the log.
This is slightly better than using a script to read an entire log because newtmgr will reuse the established BLE connection for its subsequent requests, making the process faster.
Example usage:
```
newtmgr --conntype oic_ble --connstring peer_name='nimble-bleprph' log show -a reboot_log
```
=> log show: Specify `-a` to get entire log

newtmgr/cli/res.go
The `res` (resource) command sends a generic CoAP request.  By default, the CoAP payload is specified as a series of command line arguments.
This commit allows newt to read the payload from a file instead.  There are three new command line options:
```
-B, --binfile string    Name of file containing bytes to encode as a byte string for the CoAP message body
-J, --jsonfile string   Name of file containing JSON for the CoAP message body
-R, --rawfile string    Name of file containing the raw CoAP message body
```
=> res: Allow file to specify payload

go.mod, go.sum
Pull in latest `ble` library to fix hang in catalina.
=> Fix for BLE in macOS catalina

newtmgr/bll/bll_sesn.go, newtmgr/cli/image.go, nmxact/mgmt/transceiver.go, nmxact/mtech_lora/mtech_lora_sesn.go, nmxact/nmble/ble_sesn.go, nmxact/nmble/naked_sesn.go, nmxact/nmserial/serial_sesn.go, nmxact/sesn/sesn.go, nmxact/sesn/sesn_util.go, nmxact/udp/udp_sesn.go, nmxact/xact/image.go, nmxact/xact/xact.go
image: optimize Device Firmware Upgrade (DFU)
=> Optimize DFU

.github/workflows/build.yml
This builds newtmgr and does very basic sanity test.
=> ci: Add initial Github Actions integration

docs/install/install_windows.rst
Fixes formatting issue in the section reference.
=> docs/install_windows: Fix the layout in .rst file for the PDF output
